# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  secrets:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check.outputs.valid }}
    steps:
      - name: Check for access to secrets
        id: check
        env:
          DROPBOX_CREDENTIALS_FOR_CI: ${{ secrets.DROPBOX_CREDENTIALS_FOR_CI }}
        run: |
          valid=0
          if [ ! -z "DROPBOX_CREDENTIALS" ]
          then
            echo "Secrets are available"
            valid=1
          else
            echo "Secrets are not available"
          fi
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry config virtualenvs.create false
        poetry install
    - name: Linter
      run: |
        poe lint
    - name: Tests
      env:
        DROPBOX_CREDENTIALS_FOR_CI: ${{ secrets.DROPBOX_CREDENTIALS_FOR_CI }}
      if: ${{needs.secrets.outputs.valid}} == 'true'
      run: |
        if python --version | grep -q 'Python 3.11' ; then
          poe test
        fi
